// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_DDFFQup3Xiht-nhr1UWp3Whr8ndkRg',
    appId: '1:64577390980:web:14b4c8e15c4825a491b5d1',
    messagingSenderId: '64577390980',
    projectId: 'chef-kambala',
    authDomain: 'chef-kambala.firebaseapp.com',
    storageBucket: 'chef-kambala.firebasestorage.app',
    measurementId: 'G-26D6T8S17Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23WQqi__JRMZIt1A3w-zg1HEA9bZ6RIQ',
    appId: '1:64577390980:android:e6890fac386eeb3891b5d1',
    messagingSenderId: '64577390980',
    projectId: 'chef-kambala',
    storageBucket: 'chef-kambala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbFdQCWmxmIMCgDn5rxAOeTLeuV_bHlqk',
    appId: '1:64577390980:ios:4fad73ace1e4f49191b5d1',
    messagingSenderId: '64577390980',
    projectId: 'chef-kambala',
    storageBucket: 'chef-kambala.firebasestorage.app',
    iosBundleId: 'com.example.chefKambala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbFdQCWmxmIMCgDn5rxAOeTLeuV_bHlqk',
    appId: '1:64577390980:ios:4fad73ace1e4f49191b5d1',
    messagingSenderId: '64577390980',
    projectId: 'chef-kambala',
    storageBucket: 'chef-kambala.firebasestorage.app',
    iosBundleId: 'com.example.chefKambala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx_DDFFQup3Xiht-nhr1UWp3Whr8ndkRg',
    appId: '1:64577390980:web:2ee5ada2de72531391b5d1',
    messagingSenderId: '64577390980',
    projectId: 'chef-kambala',
    authDomain: 'chef-kambala.firebaseapp.com',
    storageBucket: 'chef-kambala.firebasestorage.app',
    measurementId: 'G-M2G9G88PMF',
  );
}
